# This is a basic workflow that is manually triggered

name: demoapp

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

# This workflow makes x86_64 binaries for mac, windows, and linux.


jobs:
  mac-windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetos: [windows, darwin]
    name: demoapp for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        env:
          GOOS: ${{ matrix.targetos }}

      - name: Compile
        run: make

      - uses: actions/upload-artifact@v2
        with:
          name: demoapp ${{ matrix.targetos }}
          path: build

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, riscv64, amd64]
    name: demoapp for ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        env:
          GOARCH: ${{ matrix.arch }}

      - name: Compile
        run: make

      - uses: actions/upload-artifact@v2
        with:
          name: demoapp ${{ matrix.arch }}
          path: build
